server:
  port: 3344

spring:
  application:
    name: demo-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/chenguosi/config-center-demo.git
          search-paths:
            - springcloud-demo

eureka:
  instance:
    instance-id: demoConfig3344
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka/
